sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_152b7a30f2b4_key -iv $encrypted_152b7a30f2b4_iv
  -in assets/server.key.enc -out assets/server.key -d
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
before_script:
- export DEPLOYDIR=force-app
- export TESTLEVEL=RunAllTestsInOrg
- sfdx --version
- sfdx plugins --core
script:
- sfdx force:auth:jwt:grant --instanceurl https://login.salesforce.com  --clientid
  $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setalias UAT
- sfdx force:source:deploy --checkonly --wait 10 --sourcepath $DEPLOYDIR --targetusername
  UAT --testlevel $TESTLEVEL
